[package]
name = "bittorrent_client"
version = "0.1.0"
authors = ["Jacob Meyers <jmeyers35@gatech.edu>"]
edition = "2018"

[dependencies]
bip_bencode = "0.4.4"
bip_metainfo = "0.12.0"
clap = "2.33.0"
tokio = "0.1.21"